### PR TITLE
change these icons and bundle id

### PR DESCRIPTION
**Pull request by ItAnthonlol**
RAAAAAAHHH

### CODE REVIEW

**Comment by SolDev69** [comment]
waiting for workflow to finish

**Comment by ItAnthonlol** [comment]
Ok

**Comment by SolDev69** [comment]
it ded

**Comment by ItAnthonlol** [comment]
Ima check my crappy code

**Comment by ItAnthonlol** [comment]
Ok now let try

**Comment by SolDev69** [comment]
Fine I'll merge this

**Pull request merged**
